# NumPy Statistical Operations

Author: Gaurav Gohil

NumPy provides many powerful statistical functions that help analyze numerical data efficiently.  
These functions are widely used in data analysis, machine learning, and scientific computing.

---

## Topics Covered

1. Mean
2. Median
3. Standard Deviation
4. Variance
5. Minimum and Maximum
6. Percentiles
7. Axis-based operations

In [1]:
import numpy as np

## 1. Creating Sample Data

We first create a sample NumPy array that we will use to demonstrate statistical operations.

In [2]:
data = np.array([10, 20, 30, 40, 50])

data

array([10, 20, 30, 40, 50])

## 2. Mean (Average)

The mean represents the average value of the data.

In [3]:
mean_value = np.mean(data)

print("Mean:", mean_value)

Mean: 30.0


## 3. Median

The median is the middle value of the dataset when the values are sorted.

In [4]:
median_value = np.median(data)

print("Median:", median_value)

Median: 30.0


## 4. Standard Deviation

Standard deviation measures how spread out the numbers are in a dataset.

In [5]:
std_value = np.std(data)

print("Standard Deviation:", std_value)

Standard Deviation: 14.142135623730951


## 5. Variance

Variance measures the spread between numbers in the dataset.

In [6]:
variance_value = np.var(data)

print("Variance:", variance_value)

Variance: 200.0


## 6. Minimum and Maximum Values

NumPy provides functions to find the smallest and largest values in an array.

In [7]:
print("Minimum value:", np.min(data))
print("Maximum value:", np.max(data))

Minimum value: 10
Maximum value: 50


## 7. Percentiles

Percentiles indicate the value below which a given percentage of observations fall.

In [8]:
print("25th percentile:", np.percentile(data, 25))
print("50th percentile:", np.percentile(data, 50))
print("75th percentile:", np.percentile(data, 75))

25th percentile: 20.0
50th percentile: 30.0
75th percentile: 40.0


## 8. Statistical Operations on 2D Arrays

In [9]:
matrix = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

### Mean of entire matrix

In [10]:
np.mean(matrix)

np.float64(50.0)

### Mean by rows

In [11]:
np.mean(matrix, axis=1)

array([20., 50., 80.])

### Mean by columns

In [12]:
np.mean(matrix, axis=0)

array([40., 50., 60.])

## Conclusion

In this notebook we learned about the statistical functions provided by NumPy.

Key functions covered:

- np.mean()
- np.median()
- np.std()
- np.var()
- np.min()
- np.max()
- np.percentile()

These functions are essential for data analysis and are commonly used in machine learning workflows.