# NumPy Random Number Generation

Author: Gaurav Gohil

Random number generation is widely used in data science, machine learning, simulations, and statistical modeling.  
NumPy provides powerful functions to generate random numbers from different distributions.

---

## Topics Covered

1. Random Integers
2. Random Floats
3. Random Arrays
4. Random Choice
5. Random Normal Distribution
6. Random Seed (Reproducibility)

In [1]:
import numpy as np

## 1. Random Integer

NumPy can generate random integers within a specified range.

In [2]:
random_int = np.random.randint(1, 100)

print("Random Integer:", random_int)

Random Integer: 35


## 2. Random Float

Random floating numbers between 0 and 1 can be generated using NumPy.

In [3]:
random_float = np.random.rand()

print("Random Float:", random_float)

Random Float: 0.28014602655868515


## 3. Random Array

We can generate arrays filled with random values.

In [4]:
random_array = np.random.rand(3,3)

print("Random 3x3 Array:")
print(random_array)

Random 3x3 Array:
[[0.83972501 0.89380849 0.87596127]
 [0.39809985 0.99094748 0.50270068]
 [0.30907223 0.44912161 0.99796696]]


## 4. Random Choice

NumPy allows selecting random elements from an array.

In [5]:
numbers = [10, 20, 30, 40, 50]

random_choice = np.random.choice(numbers)

print("Randomly selected number:", random_choice)

Randomly selected number: 30


## 5. Random Normal Distribution

Normal distribution (also called Gaussian distribution) is widely used in statistics and machine learning.

In [6]:
normal_distribution = np.random.randn(5)

print("Random numbers from normal distribution:")
print(normal_distribution)

Random numbers from normal distribution:
[-0.41939083 -0.41786905 -0.03574256 -0.77705066 -0.8684215 ]


## 6. Random Seed

Setting a random seed ensures reproducibility of results.  
This means the same random numbers will be generated every time the code runs.

In [7]:
np.random.seed(42)

print("Random numbers with fixed seed:")
print(np.random.rand(3))

Random numbers with fixed seed:
[0.37454012 0.95071431 0.73199394]


## Example: Simulating Random Data

In [8]:
# Simulate 10 random values between 0 and 1

simulated_data = np.random.rand(10)

print("Simulated Data:")
print(simulated_data)

Simulated Data:
[0.59865848 0.15601864 0.15599452 0.05808361 0.86617615 0.60111501
 0.70807258 0.02058449 0.96990985 0.83244264]


## Conclusion

In this notebook we explored random number generation using NumPy.

Functions covered:

- np.random.randint()
- np.random.rand()
- np.random.choice()
- np.random.randn()
- np.random.seed()

Random number generation plays a critical role in machine learning, simulations, and statistical modeling.