# NumPy Indexing and Slicing

Author: Gaurav Gohil

This notebook explains how to access and manipulate elements in NumPy arrays using indexing and slicing techniques.

Topics Covered:
- Basic Indexing
- Negative Indexing
- Array Slicing
- 2D Array Indexing
- Boolean Indexing
- Conditional Filtering

In [1]:
import numpy as np

## 1. Creating a NumPy Array

First, we create a simple NumPy array to demonstrate indexing and slicing.

In [2]:
arr = np.array([10, 20, 30, 40, 50])

print("Array:")
print(arr)

Array:
[10 20 30 40 50]


## 2. Basic Indexing

Indexing allows us to access specific elements from an array using their position.

In [4]:
print("First element:", arr[0])
print("Second element:", arr[1])
print("Third element:", arr[2])

First element: 10
Second element: 20
Third element: 30


## 3. Negative Indexing

Negative indexing allows us to access elements from the end of the array.

In [5]:
print("Last element:", arr[-1])
print("Second last element:", arr[-2])

Last element: 50
Second last element: 40


## 4. Array Slicing

Slicing allows us to extract a portion of an array using the format:

start : stop : step

In [6]:
print("Elements from index 1 to 3:")
print(arr[1:4])

Elements from index 1 to 3:
[20 30 40]


In [7]:
print("First three elements:")
print(arr[:3])

First three elements:
[10 20 30]


In [8]:
print("Elements from index 2 to end:")
print(arr[2:])

Elements from index 2 to end:
[30 40 50]


In [9]:
print("Every second element:")
print(arr[::2])

Every second element:
[10 30 50]


## 5. 2D Array Indexing

NumPy allows indexing in multi-dimensional arrays.

In [10]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("2D Array:")
print(arr2)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print("Element at row 1 column 2:")
print(arr2[1,2])

Element at row 1 column 2:
6


In [12]:
print("First row:")
print(arr2[0])

First row:
[1 2 3]


In [13]:
print("Second column:")
print(arr2[:,1])

Second column:
[2 5 8]


## 6. Boolean Indexing

Boolean indexing allows selecting elements based on conditions.

In [14]:
data = np.array([5, 10, 15, 20, 25])

print("Numbers greater than 15:")
print(data[data > 15])

Numbers greater than 15:
[20 25]


In [15]:
print("Numbers less than 20:")
print(data[data < 20])

Numbers less than 20:
[ 5 10 15]


## 7. Conditional Filtering

We can filter arrays using logical conditions.

In [16]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

even_numbers = numbers[numbers % 2 == 0]

print("Even numbers:")
print(even_numbers)

Even numbers:
[ 2  4  6  8 10]


## Conclusion

In this notebook we learned:

- Basic indexing in NumPy arrays
- Negative indexing
- Array slicing techniques
- Indexing in 2D arrays
- Boolean indexing
- Conditional filtering

These techniques are very useful for selecting and manipulating data during data analysis and machine learning tasks.