# NumPy Matrix Operations

Author: Gaurav Gohil

Matrix operations are fundamental in Data Science, Machine Learning, and Linear Algebra.  
NumPy provides powerful functions to perform matrix calculations efficiently.

---

## Topics Covered

1. Creating Matrices
2. Matrix Addition
3. Matrix Subtraction
4. Matrix Multiplication
5. Dot Product
6. Matrix Transpose
7. Identity Matrix
8. Matrix Inverse

In [2]:
import numpy as np

## 1. Creating Matrices

In NumPy, matrices are represented as 2D arrays.

In [3]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]


## 2. Matrix Addition

Matrix addition is performed by adding corresponding elements of two matrices.

In [4]:
result_add = A + B

print("Matrix Addition:")
print(result_add)

Matrix Addition:
[[ 6  8]
 [10 12]]


## 3. Matrix Subtraction

Matrix subtraction subtracts corresponding elements.

In [5]:
result_sub = A - B

print("Matrix Subtraction:")
print(result_sub)

Matrix Subtraction:
[[-4 -4]
 [-4 -4]]


## 4. Matrix Multiplication

Matrix multiplication follows linear algebra rules.

NumPy provides multiple ways to perform this operation.

In [6]:
result_mul = np.matmul(A, B)

print("Matrix Multiplication:")
print(result_mul)

Matrix Multiplication:
[[19 22]
 [43 50]]


## 5. Dot Product

The dot product is another way to multiply matrices.

In [7]:
dot_product = np.dot(A, B)

print("Dot Product:")
print(dot_product)

Dot Product:
[[19 22]
 [43 50]]


## 6. Matrix Transpose

Transpose converts rows into columns and columns into rows.

In [8]:
transpose_A = A.T

print("Transpose of Matrix A:")
print(transpose_A)

Transpose of Matrix A:
[[1 3]
 [2 4]]


## 7. Identity Matrix

An identity matrix is a square matrix with ones on the diagonal and zeros elsewhere.

In [9]:
identity_matrix = np.eye(3)

print("Identity Matrix:")
print(identity_matrix)

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 8. Matrix Inverse

The inverse of a matrix is a matrix that, when multiplied with the original matrix, results in the identity matrix.

In [10]:
inverse_A = np.linalg.inv(A)

print("Inverse of Matrix A:")
print(inverse_A)

Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]


## Verification of Matrix Inverse

In [12]:
verification = np.dot(A, inverse_A)

print("A × A⁻¹:")
print(verification)

A × A⁻¹:
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## Conclusion

In this notebook we explored important NumPy matrix operations including:

- Matrix creation
- Matrix addition and subtraction
- Matrix multiplication
- Dot product
- Transpose
- Identity matrix
- Matrix inverse

These operations are widely used in machine learning algorithms, deep learning, and scientific computing.