# NumPy Basics for Data Science

Author: Gaurav Gohil

This notebook covers the fundamental concepts of NumPy which is one of the most important libraries in Python for Data Science.

Topics Covered:
- Creating NumPy Arrays
- Array Dimensions and Shape
- Special Arrays (Zeros, Ones, Range)
- Array Operations
- Mathematical Functions
- Indexing and Slicing
- Reshaping Arrays
- Random Numbers
- Aggregation Functions

In [4]:
import numpy as np

## 1. Creating NumPy Arrays

NumPy arrays are faster and more efficient than Python lists for numerical computations.

In [5]:
arr1 = np.array([1, 2, 3, 4, 5])

print("1D Array:")
print(arr1)

1D Array:
[1 2 3 4 5]


In [6]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("2D Array:")
print(arr2)

2D Array:
[[1 2 3]
 [4 5 6]]


## 2. Array Shape and Dimensions

NumPy provides useful attributes to understand the structure of arrays.

In [7]:
print("Shape of array:", arr2.shape)
print("Number of dimensions:", arr2.ndim)
print("Total elements:", arr2.size)

Shape of array: (2, 3)
Number of dimensions: 2
Total elements: 6


## 3. Creating Special Arrays

NumPy provides functions to generate arrays filled with zeros, ones, or a range of numbers.

In [8]:
zeros_array = np.zeros((2,3))
print("Zeros Array:")
print(zeros_array)

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
ones_array = np.ones((3,3))
print("Ones Array:")
print(ones_array)

Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
range_array = np.arange(0,10,2)

print("Range Array:")
print(range_array)

Range Array:
[0 2 4 6 8]


## 4. Array Operations

NumPy supports element-wise operations between arrays.

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Addition:")
print(a + b)

print("Subtraction:")
print(a - b)

print("Multiplication:")
print(a * b)

Addition:
[5 7 9]
Subtraction:
[-3 -3 -3]
Multiplication:
[ 4 10 18]


## 5. Mathematical Functions

NumPy provides built-in mathematical functions for numerical computations.

In [12]:
numbers = np.array([4,9,16])

print("Square Root:")
print(np.sqrt(numbers))

print("Mean:")
print(np.mean(numbers))

print("Sum:")
print(np.sum(numbers))

Square Root:
[2. 3. 4.]
Mean:
9.666666666666666
Sum:
29


## 6. Array Indexing

Indexing allows us to access specific elements in an array.

In [13]:
arr = np.array([10,20,30,40,50])

print("First element:", arr[0])
print("Last element:", arr[-1])

First element: 10
Last element: 50


## 7. Array Slicing

Slicing allows us to extract portions of an array.

In [14]:
print("Slice from index 1 to 4:")
print(arr[1:4])

Slice from index 1 to 4:
[20 30 40]


## 8. Reshaping Arrays

Reshaping changes the structure of the array without changing its data.

In [15]:
reshape_arr = np.arange(1,10)

reshaped = reshape_arr.reshape(3,3)

print("Reshaped Array:")
print(reshaped)

Reshaped Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 9. Random Numbers

NumPy can generate random numbers which are useful in simulations and machine learning.

In [16]:
random_array = np.random.rand(3,3)

print("Random Array:")
print(random_array)

Random Array:
[[0.98855672 0.42258779 0.33315591]
 [0.40413987 0.2808321  0.73242197]
 [0.93598306 0.10544815 0.40144587]]


## 10. Aggregation Functions

Aggregation functions summarize the data in arrays.

In [17]:
data = np.array([5,10,15,20])

print("Maximum value:", np.max(data))
print("Minimum value:", np.min(data))
print("Average value:", np.mean(data))
print("Total sum:", np.sum(data))

Maximum value: 20
Minimum value: 5
Average value: 12.5
Total sum: 50


## Conclusion

In this notebook we learned:

- Creating NumPy arrays
- Array shape and dimensions
- Special arrays (zeros, ones, range)
- Mathematical operations
- Indexing and slicing
- Reshaping arrays
- Random number generation
- Aggregation functions

NumPy is the foundation of many Data Science libraries such as Pandas, Scikit-Learn, and TensorFlow.